-- NL互換ビュー: ecore.db(N_*) を NL_* 名で参照できるようにする
PRAGMA foreign_keys=OFF;

-- 既存があれば置き換え
DROP VIEW IF EXISTS NL_SE_RACE_UMA;
DROP VIEW IF EXISTS NL_RA_RACE;
DROP VIEW IF EXISTS NL_O1_ODDS_TANFUKUWAKU;

-- 出馬表(馬) 相当: NL_SE_RACE_UMA
CREATE VIEW NL_SE_RACE_UMA AS
SELECT
  Year      AS idYear,
  MonthDay  AS idMonthDay,
  JyoCD     AS idJyoCD,
  RaceNum   AS idRaceNum,
  Umaban,
  KettoNum,
  Bamei,
  KisyuRyakusyo,
  Futan,
  ChokyosiRyakusyo,
  BanusiName,
  KakuteiJyuni,
  DochakuTosu,
  Time,
  ChakusaCD,
  Jyuni1c,
  Jyuni2c,
  Jyuni3c,
  Jyuni4c,
  KyakusituKubun
FROM N_UMA_RACE;

-- レース(見出し) 相当: NL_RA_RACE
CREATE VIEW NL_RA_RACE AS
SELECT
  Year      AS idYear,
  MonthDay  AS idMonthDay,
  JyoCD     AS idJyoCD,
  RaceNum   AS idRaceNum,
  -- 互換ヘッダ候補
  COALESCE(RaceInfoHondai, RaceName, RaceNameJ, Racename) AS RaceInfoHondai,
  RaceInfoFukudai,
  TrackCD,
  Kyori,
  SyussoTosu
FROM N_RACE;

-- オッズO1 互換: 参照エラー回避用の空ビュー（列名を用意して0行を返す）
CREATE VIEW NL_O1_ODDS_TANFUKUWAKU AS
SELECT * FROM (
  SELECT
    CAST(NULL AS TEXT) AS idYear,
    CAST(NULL AS TEXT) AS idMonthDay,
    CAST(NULL AS TEXT) AS idJyoCD,
    CAST(NULL AS TEXT) AS idRaceNum,
    -- 0..27 の単勝表示用ペア(Ux, Ox)
    CAST(NULL AS TEXT) AS U0,  CAST(NULL AS TEXT) AS O0,
    CAST(NULL AS TEXT) AS U1,  CAST(NULL AS TEXT) AS O1,
    CAST(NULL AS TEXT) AS U2,  CAST(NULL AS TEXT) AS O2,
    CAST(NULL AS TEXT) AS U3,  CAST(NULL AS TEXT) AS O3,
    CAST(NULL AS TEXT) AS U4,  CAST(NULL AS TEXT) AS O4,
    CAST(NULL AS TEXT) AS U5,  CAST(NULL AS TEXT) AS O5,
    CAST(NULL AS TEXT) AS U6,  CAST(NULL AS TEXT) AS O6,
    CAST(NULL AS TEXT) AS U7,  CAST(NULL AS TEXT) AS O7,
    CAST(NULL AS TEXT) AS U8,  CAST(NULL AS TEXT) AS O8,
    CAST(NULL AS TEXT) AS U9,  CAST(NULL AS TEXT) AS O9,
    CAST(NULL AS TEXT) AS U10, CAST(NULL AS TEXT) AS O10,
    CAST(NULL AS TEXT) AS U11, CAST(NULL AS TEXT) AS O11,
    CAST(NULL AS TEXT) AS U12, CAST(NULL AS TEXT) AS O12,
    CAST(NULL AS TEXT) AS U13, CAST(NULL AS TEXT) AS O13,
    CAST(NULL AS TEXT) AS U14, CAST(NULL AS TEXT) AS O14,
    CAST(NULL AS TEXT) AS U15, CAST(NULL AS TEXT) AS O15,
    CAST(NULL AS TEXT) AS U16, CAST(NULL AS TEXT) AS O16,
    CAST(NULL AS TEXT) AS U17, CAST(NULL AS TEXT) AS O17,
    CAST(NULL AS TEXT) AS U18, CAST(NULL AS TEXT) AS O18,
    CAST(NULL AS TEXT) AS U19, CAST(NULL AS TEXT) AS O19,
    CAST(NULL AS TEXT) AS U20, CAST(NULL AS TEXT) AS O20,
    CAST(NULL AS TEXT) AS U21, CAST(NULL AS TEXT) AS O21,
    CAST(NULL AS TEXT) AS U22, CAST(NULL AS TEXT) AS O22,
    CAST(NULL AS TEXT) AS U23, CAST(NULL AS TEXT) AS O23,
    CAST(NULL AS TEXT) AS U24, CAST(NULL AS TEXT) AS O24,
    CAST(NULL AS TEXT) AS U25, CAST(NULL AS TEXT) AS O25,
    CAST(NULL AS TEXT) AS U26, CAST(NULL AS TEXT) AS O26,
    CAST(NULL AS TEXT) AS U27, CAST(NULL AS TEXT) AS O27
  )
WHERE 1=0;
